version: '3'

services:
  web:
    image: sugandhdevops/web-cd:latest
    restart: always
    build:
      context: .
    ports:
      - ${HTTP_PORT}:5000
    volumes:
      - .:/usr/src/app
    env_file: .env
  
  mssql:
    image: sugandhdevops/db-cd:latest
    volumes:
      - ./db:/usr/src/app
      - ./mssql:/var/opt/mssql/data
    working_dir: /usr/src/app
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
