name: docker cd
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: docker login
      env:
        USER: ${{ secrets.DOCKER_USERNAME }}
        PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "$USER" -p "$PASS"
    - name: env setup
      run: test -f .env || cp .env.sample .env
    - name: build images
      run: docker-compose build --no-cache
    - name: docker push
      run: docker-compose push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ~/dotnet-cd-2
          # pull git updates
          git pull origin master
          # rm local images cache
          docker rmi --force elhardoum/dotnet-cd-demo:latest || true
          docker rmi --force elhardoum/dotnet-cd-demo-db:latest || true
          # pull images from remote
          docker-compose build --pull --no-cache
          docker-compose up -d --force-recreate
